# Generated by Django 5.2.5 on 2025-08-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=50, unique=True)),
                ('veh_make', models.CharField(blank=True, max_length=100, null=True)),
                ('body_model', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vin_number', models.CharField(max_length=100, unique=True)),
                ('tag_no', models.CharField(blank=True, max_length=50, null=True)),
                ('body_year', models.PositiveIntegerField(blank=True, null=True)),
                ('next_ps_date', models.DateField(blank=True, null=True)),
                ('inservice_date', models.DateField(blank=True, null=True)),
                ('vehicle_class', models.CharField(blank=True, max_length=50, null=True)),
                ('veh_model', models.CharField(blank=True, max_length=100, null=True)),
                ('chassis_year', models.PositiveIntegerField(blank=True, null=True)),
                ('orig_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cap', models.PositiveIntegerField(blank=True, null=True)),
                ('body_make', models.CharField(blank=True, max_length=100, null=True)),
                ('body_no', models.CharField(blank=True, max_length=50, null=True)),
                ('trans_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_manuf', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_model', models.CharField(blank=True, max_length=100, null=True)),
                ('eng_type', models.CharField(blank=True, max_length=100, null=True)),
                ('eng_manuf', models.CharField(blank=True, max_length=100, null=True)),
                ('eng_model', models.CharField(blank=True, max_length=100, null=True)),
                ('eng_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('last_in_shop', models.DateField(blank=True, null=True)),
                ('last_ps_date', models.DateField(blank=True, null=True)),
                ('next_oil_change', models.DateField(blank=True, null=True)),
                ('fuel_gal', models.FloatField(blank=True, null=True)),
                ('last_fuel_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('ytd_fuel', models.FloatField(blank=True, null=True)),
                ('current_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('sch_begin_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_opr_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('chassis_no', models.CharField(blank=True, max_length=100, null=True)),
                ('last_time_in', models.DateTimeField(blank=True, null=True)),
                ('last_time_out', models.DateTimeField(blank=True, null=True)),
                ('last_oil_change', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gvw_front', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tire_size', models.CharField(blank=True, max_length=50, null=True)),
                ('gvw_rear', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wheel_base', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('wheel_chair', models.BooleanField(default=False)),
                ('assigned_shop', models.CharField(blank=True, max_length=100, null=True)),
                ('insp_group', models.CharField(blank=True, max_length=100, null=True)),
                ('bus_driver', models.CharField(blank=True, max_length=100, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('trade_code', models.CharField(blank=True, max_length=50, null=True)),
                ('last_pm_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('next_pm_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('last_pm_date', models.DateField(blank=True, null=True)),
                ('next_pm_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': True,
            },
        ),
    ]
