# Generated by Django 5.2.5 on 2025-08-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'managed': False},
        ),
    ]
