# Generated by Django 5.2.5 on 2025-08-25 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
    ]
