# Generated by Django 5.2.5 on 2025-08-25 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_location_options_alter_location_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='shop_locations',
        ),
    ]
