# Generated by Django 5.2.5 on 2025-09-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_location_table'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='employee_id',
            new_name='vendor_id',
        ),
      
    ]
