# Generated by Django 5.2.5 on 2025-09-05 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_employee_id_vendor_vendor_id_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
    ]
