# Generated by Django 5.2.5 on 2025-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='task',
            table='work_order_tasks',
        ),
    ]
