# Generated by Django 5.2.5 on 2025-09-09 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_task_options_task_completed_at_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='labor_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='other_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='outsourced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.vendor'),
        ),
        migrations.AddField(
            model_name='task',
            name='parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='parts_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
