# Generated by Django 5.2.5 on 2025-09-10 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': False},
        ),
    ]
