# Generated by Django 5.2.5 on 2025-09-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_employee_department_alter_employee_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True},
        ),
    ]
